# Generated by Django 3.0.8 on 2020-10-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend_class_app', '0005_attendee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='units',
            new_name='unit_taken',
        ),
    ]
